### ISSUE TITLE
Add templates into zserio language

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#144]
Implement support for templates into zserio language using new keyword `template`. Something like the following:

```
template <T>
struct TemplatedStruct
{
    bool hasValue;
    T    value if hasValue;
};
```

**Comment by mikir** [comment]
We suggest to implement the zserio templates using Java notation:

```
struct TemplatedStruct<T>
{
    bool hasValue;
    T    value if hasValue;
};

struct TemplatedStructHolder
{
    TemplatedStruct<uint8>  struct1;
    TemplatedStruct<uint16> struct2;
};
```
Because we should support all generators (even these which do not support templates), we suggest to replace all zserio template instantiations by normal types during zserio compilation.

Example:
```
struct MyFirstZserioTemplate<TYPE>
{
    bool    hasGenericType;
    TYPE    type if hasGenericType;
};

struct TemplateHolder
{
    MyFirstZserioTemplate<uint8> instantiation;
};
```
The previous example will generates two none template classes `MyFirstZserioTemplate_uint8` and `TemplateHolder`.

In another words, the previous example will be changed by zserio into the following

```
struct MyFirstZserioTemplate_uint8
{
    bool    hasGenericType;
    uint8   type if hasGenericType;
};

struct TemplateHolder
{
    MyFirstZserioTemplate_uint8 instantiation;
};
```

**Comment by 0xDEAD** [comment]
In which package will the "unrolled" generated classes be located? Will the dependency between packages change?

Some Examples to make the questions clear:

1. 
MyFirstZserioTemplate is in package A and is used in package B with TYPE=int8.
(which results in a generated class MyFirstZserioTemplate_uint8).
-> in this case the place doesn't matter, as uint8 is a basetype

2.
MyFirstZserioTemplate is in package A and is used in package B with TYPE=some-struct-defined-in-B.
(which results in a generated class MyFirstZserioTemplate_somestruct).
-> the generated code has to be located in package B, because the type some-struct is not known in package A

3.
MyFirstZserioTemplate is in package A and is used in package B with TYPE=int8 and is used in package C with type=int8
As we learned in 2, the code must be generated into package B and C. But as two classes (with the exact same code) are generated, they will not be "the same" and you will not be able to assign one instance to another across packages.


Do we agree, that those implications are OK?

**Comment by mikir** [comment]
Good point. Your implications are ok if some "unrolling" or preprocessing of zserio sources will be implemented. However, zserio core will implement this feature in memory by using data structures. And zserio core sees each type in each package.

The current idea is that each instantiated template will be generated in the package/namespace where template declaration is located. If the same template will be instantiated multiple times, it will be generated only once.
