### ISSUE TITLE
C++11: optional access unnecessary

### ISSUE THREAD

**Issue by PeachOS** [ndsev/zserio#146]
The current C++11 emitter generally generates the following methods for a complex field (example taken from the tutorial code):
```
::zserio::OptionalHolder<uint16_t>& getBonus();
const ::zserio::OptionalHolder<uint16_t>& getBonus() const;

void setBonus(const ::zserio::OptionalHolder<uint16_t>& bonus_);
void setBonus(::zserio::OptionalHolder<uint16_t>&& bonus_);

bool hasBonus() const;
```

Returning the optional holder appears to be unnecessary though. As a careful application I would call `hasBonus()` first to check, whether the field is set. The following `getBonus()` could then immediately return the internal value. I will not call `getBonus().hasValue()` anyway, as that was already done.

(**1**) My first proposal  is to change the getters to directly return the value. The implementation of the getter can simply be `return m_bonus_.getValue()` in this specific case.

A similar thing is true for the setters. Setting an optional is very unintuitive. Either I set the value or I don't. The optional is then just an internal technical detail.

(**2**) So my second proposal is to change all setters to directly take the value. The implementation can then adjust its internal optional field.

**Comment by PeachOS** [comment]
Just for completeness:
In case the setter was used to clear the optional holder I would rather prefer an additional method like `void clearBonus()` for that.

**Comment by mikir** [comment]
Thanks for sharing your idea. We can implement API with or without `OptionalHolder` but we have to keep in mind the following requirements:

1. Getter should not return some "default" value if optional member is not present because this could potentially hide some mistakes. Getter should throw exception.
1. It must be possible to remove already set optional member.
1. It must be possible to check if optional member is set.
1. Has method must return true iff optional expression (if clause) is true. It doesn't necessarily mean that optional member is set. However for auto optional members, this method is redundant to checking method.

The following is our suggestion how to fulfill previous requirements without `OptionalHolder` applied for the `Bonus` example:

```
uint16_t getBonus();
void setBonus(uint16_t bonus_);
void clearBonus();
bool isSetBonus();

// The following won't be generated because this is an auto optional.
// It will be generated for non-auto optionals only.
// bool hasBonus() const;
```

**Comment by Mi-La** [comment]
Just a note. With optional holder on the interface, you still can set the value directly without passing an optional holder. Optional holder has a constructor from the value type and it even supports move sematics.
```
std::vector<uint16_t> createArray(); // some function which creates array
setOptionalArray(createArray()); // the array is moved to optional holder since new optional holder is created automatically from std::vector<uint16_t> rvalue reference
```
Same with set bonus (where move has no sense):
```
uint16_t bonus = 1000;
setBonus(bonus);
```

**Comment by mikir** [comment]
Please note that we use `OptionalHolder` in generated SQL Table Rows classes as well:

```
class ConstParamTable
{
public:
    class Row
    {
    public:
        Row() = default;
        ~Row() = default;

        Row(const Row& other);
        Row& operator=(const Row& other);

        Row(Row&& other);
        Row& operator=(Row&& other);

        const ::zserio::OptionalHolder<uint32_t>& getBlobId() const;
        void setBlobId(const ::zserio::OptionalHolder<uint32_t>& blobId_);

        ::zserio::OptionalHolder<::std::string>& getName();
        const ::zserio::OptionalHolder<::std::string>& getName() const;
        void setName(const ::zserio::OptionalHolder<::std::string>& name_);
        void setName(::zserio::OptionalHolder<::std::string>&& name_);
...
```

There is very similar problem. We needed `isNull` and `setNull` methods, therefore we use `OptionalHolder` directly. If we decide to get rid of `OptionalHolder` from generated API, we will have to change probably this as well.

**Comment by PeachOS** [comment]
@mikir I am very fine with the 4 above points and with a an SQL API that simply looks the same. That might even make the SQL access prettier. I think something like `row.has_name() and row.has_stuff()` is still much prettier than `row.getName().hasValue() and row.getStuff().hasValue()`.

@Mi-La True! Considering that one can internally just replace the content of an optional holder, the implicit conversion is still an unnecessary feature though. But most of my suggested API changes are just based on the fact, that the getter is not comfortable at all.

**Comment by mikir** [comment]
TB: We will wait a little bit for further opinions. Currently, API without OptionalHolder as suggested is preferred. Just please use isBonusSet() instead of isSetBonus().

**Comment by mikir** [comment]
We have removed OptionalHolder from API.

At the end, we have decided not to support `isSet`method because such method has sense only for database compilers (only for applications which writes data to binary stream). And normal application could know if it has already set optional member or not.

We have also renamed `clear` method to `reset` method which corresponds better what it does.

The following is the final solution applied for the Bonus example:
```
uint16_t getBonus();
void setBonus(uint16_t bonus_);
void resetBonus();
bool hasBonus();
```
Similarly, we have changed the generated SQL Table rows (they have `get`, `set`, `reset` and `has` methods as well).
