### ISSUE TITLE
Generated template file names too long

### ISSUE THREAD

**Issue by KRE02** [ndsev/zserio#158]
The generated file names for templated types can exceed the max. file name length, which will cause the C++ generator to fail.

Input (`long_template_parameter_name_test.zs`):
```
package long_template_parameter_name_test;

struct Templated<A, B, C, D, E, F, G> {
    /* Dummy */
};

struct Type {
    /* Dummy */
};

struct Container {
    Templated<
        long_template_parameter_name_test.Type,
        long_template_parameter_name_test.Type,
        long_template_parameter_name_test.Type,
        long_template_parameter_name_test.Type,
        long_template_parameter_name_test.Type,
        long_template_parameter_name_test.Type,
        long_template_parameter_name_test.Type> dummy;
};
```

Generate C++ sources using:
```
zserio -cpp . -src . long_template_parameter_name_test.zs
```

The generator fails with the following message:
```
[ERROR] C++11 Generator: ./long_template_parameter_name_test/Templated_long_template_parameter_name_test_Type_long_template_parameter_name_test_Type_long_template_parameter_name_test_Type_long_template_parameter_name_test_Type_long_template_parameter_name_test_Type_long_template_parameter_name_test_Type_long_template_parameter_name_test_Type.h (File name too long)
```

**Comment by mikir** [comment]
There is a limitation for file name to 255 characters in Linux and Windows. Besides of that, Windows applications which do not use new API (e.g. MinGW compiler, FindBugs), still have limitation for whole path to 260 characters.

Because of that, we have decided to change the naming of generated template instantiations in the following way:

1. Template instantiations will be named using argument names without package names. Example:
```
Templated_Type_Type_Type_Type_Type_Type_Type
```

2. If the name from point 1. is longer than 64 characters, it will be truncated to 63 characters and appended by '_' postfix. Example:
```
struct ThisIsVeryVeryVeryLongNamedStructure
{
    string data;
};

struct TemplatedStruct<T, U>
{
    T field1;
    U field2;
};

struct StructLongTemplateArgument
{
    TemplatedStruct<ThisIsVeryVeryVeryLongNamedStructure,
                    ThisIsVeryVeryVeryLongNamedStructure> structNameOverflow;
};
```
The name `TemplatedStruct_ThisIsVeryVeryVeryLongNamedStructure_ThisIsVeryVeryVeryLongNamedStructure` is too long and it will be truncated to `TemplatedStruct_ThisIsVeryVeryVeryLongNamedStructure_ThisIsVery_`.

3. If the name from point 1. or point 2. clashes with another template instantiation name, both names will be appended by '_' and 8 bytes hash code. Example:

```
package templates.struct_template_clash_other_template;

struct Test_A<T>
{
    T value;
};

struct Test<T>
{
    T value;
};

struct A_uint32
{
    uint32 value;
};

struct InstantiationNameClashOtherTemplate
{
    Test_A<uint32> t1;
    Test<A_uint32> t2;
};
```
Names `Test_A_uint32` clashes, therefore the hash codes will be appended: `Test_A_uint32_5D68B0C2` and `Test_A_uint32_FA82A3B7`.

4. If generated template instantiation name with hash code is longer than 64 characters, the name before '_' and hash code will be truncated to 55 characters.

5. If generated template instantiation name with hash code clashes, compilation error is reported.
