### ISSUE TITLE
Multiple instantiations of template with same base type not working

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio#160]
The following schema generates an error:

```
instantiate Template<uint32> FirstInstanceClass;
instantiate Template<uint32> SecondInstanceClass; 

struct Template<T>
{
  T value;
};

```
We definitely need to be able to do something like this. This demo code does not seem to be obvious but once we are using subtypes as arguments that have their own definition it is needed.

Example:

subtype varuint32 LengthInCm;
subtype varuint32 LengthInMeter;

instantiate Template<LengthInCm> FirstInstanceClass;
instantiate Template<LengthInMeter> SecondInstanceClass; 

struct Template<T>
{
  T value;
};

**Comment by mikir** [comment]
Hmmm. Not sure about your use case but `subtype` is not suitable?

```
instantiate Template<uint32> FirstInstanceClass;
subtype FirstInstanceClass SecondInstanceClass; 
```

The problem with multiple instantiations is that user can use `Template<uint32>` together with new `instantiate` names. Example:

```
instantiate Template<uint32> FirstInstanceClass;
instantiate Template<uint32> SecondInstanceClass; 

struct Template<T>
{
    T value;
};

struct Holder
{
    FirstInstanceClass instance1;
    SecondInstanceClass instance2;
    Template<uint32> instance3; // We cannot map Template<uint32>
                                // to FirstInstanceClass or SecondInstanceClass
};
```

So, once we allow multiple instantiations then `FirstInstanceClass`, `SecondInstanceClass` and `Template<uint32>` will be completely different types.

But in this case, the following can't work:

```
struct Test<T>
{
    T value;
};

struct Other<T>
{
    T value;
};

struct InstantiateTemplateArgument
{
    // Test<string> should be named as Str but this won't work
    // because Test<string> and Str are different types
    Other<Test<string>> other;
};

instantiate Test<string> Str;
```

Let's discuss.

**Comment by mikir** [comment]
Aha, ok. I am sorry this is my fault I did not understand your problem properly. :-) So, we are not able to allow the following

```
instantiate Template<varuint32> FirstInstanceClass;
instantiate Template<varuint32> SecondInstanceClass; 
```

but we can allow your use case:

```
subtype varuint32 LengthInCm;
subtype varuint32 LengthInMeter;

instantiate Template<LengthInCm> FirstInstanceClass;
instantiate Template<LengthInMeters> SecondInstanceClass;
```

This is because we can claim that template instantiation using subtype (alias) has different type to template instantiation using base type. This might be not very intuitive because suddenly alias is not alias in template instantiation but at least it is feasible. But we must be careful and to think about all pros and cons before such change. 

For example, we got inspiration for this templates behavior from C++. The template instantiation using typedef has the same type as template instantiation using base type.

Example of working C++ code:

```
#include <vector>
#include <iostream>

void function(std::vector<int>& something)
{
    std::cout << "In function!" << std::endl;
};

typedef int MyInteger;

int main(void)
{
    std::vector<MyInteger> something;
    function(something); // this works because std::vector<MyInteger> has the same type as std::vector<int>
    std::cout << "Success!" << std::endl;
}
```

Such template constructs using subtypes won't even work for native C++ templates. So, if we change this in zserio and template instantiations using subtypes will have different types, we won't be able to make any "smart" C++ generator which will use directly native C++ templates.

We will make some internal brainstorming about this and I will come back to you. It might be we will find out some another solution (new keyword?).

**Comment by mikir** [comment]
We are not able to find out something better. So far we can see the following solutions:

1. To leave it as it is to mimic C++ templates behavior.
2. To change `subtype` meaning. It will define another unique type not alias type. Not to introduce mess, `subtype` will define another unique type not only for template instantiations but for normal types as well.
3. To change `subtype` meaning only for template instantiations. Not recommended.
4. To introduce new special `subtype` keyword for templates. Like `newtype`. Not very intuitive. Not recommended.

**Comment by mikir** [comment]
We will close it as not necessary any more. Just open it again if this become an issue again.
