### ISSUE TITLE
Python: Generate properties instead of getters/setters

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#233]
Currently, Python generates getters and setters for access to fields to be consistent with other generators (C++ or Java).

However, it would be more pythonic to use properties in Python (x.y instead of x.getY).

**Comment by Mi-La** [comment]
Please note that using getter and setters is not only motivated to be consistent with Java and C++. The `get` and `set` prefixes are also very handy to prevent any name clashing. Consider following example:

```
struct ClashingProp
{
    uint32 bitSizeOf;
};
```
This would generate something like this if properties were used:
```python
class ClashingProp:
    def __init__(self) -> None:
        self._bitSizeOf_ = int() # type: int
    # ....
    def bitSizeOf(self, bitPosition: int = 0) -> int: # built-in zserio method
        endBitPosition = bitPosition
        endBitPosition += 4
        return endBitPosition - bitPosition
    # ....
    bitSizeOf = property(getBitSizeOf, setBitSizeOf)
```
Now it would be impossible to call `bitSizeOf` method since it's overridden by the property. Note that in other compound there might be also some internal members and it would be also very difficult to prevent name clashing. And what if a user names a field like `__init__`, `__eq__`, etc.?

**Comment by mikir** [comment]
One solution for the property name clashing could be to add some prefix, like 'prop', 'p' or 'x'. Example:

```
struct ClashingProp
{
    uint32 bitSizeOf;
};
```

```
class ClashingProp:
    def __init__(self) -> None:
    @classmethod
    def fromReader(cls: typing.Type['ClashingProp'], reader: zserio.BitStreamReader) -> 'ClashingProp':
    @classmethod
    def fromFields(cls: typing.Type['ClashingProp'], bitSizeOf_: int) -> 'ClashingProp':
    def getBitSizeOf(self) -> int:
    def setBitSizeOf(self, bitSizeOf_: int) -> None:
    def bitSizeOf(self, bitPosition: int = 0) -> int:
    def initializeOffsets(self, bitPosition: int) -> int:
    def read(self, reader: zserio.BitStreamReader) -> None:
    def write(self, writer: zserio.BitStreamWriter, *, callInitializeOffsets: bool = True) -> None:

    # ....
    propBitSizeOf = property(getBitSizeOf, setBitSizeOf) // no clash whatever name for field will be used!
```

We think (if we don't forget for something) that if we use some prefix which does not clash with the beginning of stable generated names (from(Reader), get, set, bit(SizeOf), initialize, etc...), there will be no clash whatever name for field will be used in schema.

Because using prefix for properties is annoying, we might try to do it vice versa and to add some prefixes for stable generated names. But this solution does not work and can be easily broken:

```
struct ClashingProp
{
    uint32 bitSizeOf;
    uint32 xBitSizeOf;
};
```

```
class ClashingProp:
    def __init__(self) -> None:
    @classmethod
    def xFromReader(cls: typing.Type['ClashingProp'], reader: zserio.BitStreamReader) -> 'ClashingProp':
    @classmethod
    def xFromFields(cls: typing.Type['ClashingProp'], bitSizeOf_: int) -> 'ClashingProp':
    def xGetBitSizeOf(self) -> int:
    def xSetBitSizeOf(self, bitSizeOf_: int) -> None:
    def xGetXBitSizeOf(self) -> int:
    def xSetXBitSizeOf(self, bitSizeOf_: int) -> None:
    def xBitSizeOf(self, bitPosition: int = 0) -> int:
    def xInitializeOffsets(self, bitPosition: int) -> int:
    def xRead(self, reader: zserio.BitStreamReader) -> None:
    def xWrite(self, writer: zserio.BitStreamWriter, *, callInitializeOffsets: bool = True) -> None:

    # ....
    bitSizeOf = property(xGetBitSizeOf, xSetBitSizeOf)
    # ....
    xBitSizeOf = property(xGetXBitSizeOf, xSetXBitSizeOf) // this will clash with xBitSizeOf method!
```

To put it all together, we are currently able to find out only annoying solution with some prefix which cannot be never broken.

**Comment by MisterGC** [comment]
What about providing a prefix by default but allow the user redefine it and also allow to make it empty "". That means the default impl. avoids clashes and it's the user responsibility if he decide to set it empty. Ideally clashes would be detected - What do you think?

**Comment by Mi-La** [comment]
We will introduce new option group for python extension (`-withPythonPropPrefix` *(default)* / `-withoutPythonPropPrefix`).

By default, the 'prop' prefix will be prepended to each property name. Thanks to the prefix, we automatically resolve all possible clashes, e.g. with: getters/setter/indicators for fields and parameters, functions from generated API (`read`,`write`, ...), generated private members (e.g. fields, starting with `_`), python internal functions starting with `__` (e.g. `__init__.py`).

When user specifies the `-withoutPythonPropPrefix`, will have have to do some extra checks to prevent name clashings which wouldn't be detected until the code is executed. To make it simple, we will do the following checks based on the field names:
   * field name cannot start with `_` (easily prevents clashes with private members, and even with python internal functions starting with `__`)
   * field name will be checked against generated API methods for current compound type (`read`, `write`, `fromFields`, `connection`, etc.)
   * field name will be checked against generated getters/setters/indicators for other fields (`getField1`, `hasField1`, etc.)
      ```
      struct Test
      {
          uint32 field1;
          uint32 getField1; // property 'getField1' can clash with getter for 'field1'
      };
      ```
Since clashing makes the generated code unusable, we will fire an error once any check fails.

**Comment by Mi-La** [comment]
Currently `zserio` supports both setters/getters and properties for parameters and fields.

What about `choiceTag()` method in Unions? Should it be a property? And should we then support also both "getter" and property? What about naming?

Maybe supporting both properties and setters/getters is little bit schizofrenic. Currently we have introduced `-withPythonPropPrefix` option, but maybe we could just switch it to `-withPythonProperties` which would be disabled by default to prevent clashing, but once enabled, the getters/setters would be changed to properties and properties would have names without prefix. And if the schema did use field names which did clash with generated API, the properties version would be unusable.

**Comment by Mi-La** [comment]
We will use `-withPythonProperties` to switch between getters/setters solution and properties solution.
