### ISSUE TITLE
NDS Map Creation

### ISSUE THREAD

**Issue by sp062** [ndsev/zserio#271]
Trying to create NDS Map Based on Document but not able to create NDS Map data is their any tools to use or any tutorials to verify

**Comment by mikir** [comment]
Unfortunately, we are not able to guess from the description what you are trying to do and what is not working. Please, write us more detailed information about the problem with zserio compiler.

**Comment by sp062** [comment]
Any document or tutorial to create NDS Map?
Because i was stuck in begin itself.

**Comment by mikir** [comment]
This project (zserio) is a generic serialization framework which allows you to serialize and deserialize data in a compact and efficient way. It is used by NDS but it is not a tool which creates NDS database. Please contact NDS support if you are NDS member or please check [NDS web site](https://nds-association.org/) otherwise.
