### ISSUE TITLE
NDS Database and C++ and Java API

### ISSUE THREAD

**Issue by Puneethsp** [ndsev/zserio#272]
Trying to create NDS database BLOB as shown in sample data. Not able to create NDS db for our data, Referring NDS Documents in website but not able to do. Please help me with any doc or any tools.

**Comment by mikir** [comment]
Unfortunately, we are not able to guess from the description what you are trying to do and what is not working. Please, write us more detailed information about the problem with zserio compiler. For example, which sample do you use?

**Comment by Puneethsp** [comment]
Want to create a NDS Map, But not able to create. Stuck in creating .NDS database

**Comment by mikir** [comment]
This project (zserio) is a generic serialization framework which allows you to serialize and deserialize data in a compact and efficient way. It is used by NDS but it is not a tool which creates NDS database. Please contact NDS support if you are NDS member or please check [NDS web site](https://nds-association.org/) otherwise.
