### ISSUE TITLE
Doc emitter: Markdown comments not rendered if no empty line between struct and comment

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio#280]
The latest documentation HTML emitter does not correctly render markdown comments.
Markdown comments `/*!` are only processed to HTML if there is an empty line between the comment and the structure/enum etc.

```
/*!
Some markdown comment
!*/
struct Test
{ };
```
renders the comment being part of the code block in the generated HTML, 
whereas
```
/*!
Some markdown comment
!*/

struct Test
{ };
```
renders it correctly to HTML.
This is true for all language items, including `package`, `import`, etc.

**Comment by mikir** [comment]
This was a solution how to put users power to influence HTML output and to distinguish between comments which must be generated as HTML before code section and comments which must be a part of code section.

Some more information follows.

Definitions :

- Classic documentation comment: ‘/** */’. 
- Markdown documentation comment: ‘/*! */’. 
- Sticky documentation comment is a comment which does not have blank line afterwards 
- Floating documentation comment is a comment which has blank line afterwards 
- One-liner documentation comment is a comment written on one line in the schema 

Behavior:

- Classic and Markdown documentation comments are equal 
- Sticky documentation comments are rendered in the code sections. 
- Floating documentation comments are rendered before the code sections. 
- One-liner comments are rendered on one line. 

If this feature is not intuitive or brings unexpected problems, we will have to revise it somehow. Probably we should introduce some documentation of HTML generator as well.

**Comment by Mi-La** [comment]
Since the new documentation has one HTML page per zserio package, we have introduced the new logic of *sticky* and *floating* comments. The purpose is to allow to place a (floating) comment almost anywhere in the package documentation - i.e. the rendered comment seems to belong to the package rather than to a compound type or another entity and it is rendered exactly where it's placed in the zserio source. Sitcky comments always belong to some entity (compound, constant, import, etc.)

**Comment by fklebert** [comment]
OK, I understand the idea of floating and sticky.
But what is the use case of having a sticky markdown comment? This never gets rendered correctly in any representation then.
The whole purpose of having markdown comments is that we can format them to make them look nice and add images and so on.
So while I like the idea of sticky and floating for usual doc comments, I cannot see a use case for markdown comments being sticky.

**Comment by Mi-La** [comment]
The markdown comments are still rendered to HTML, they are just styled to look like the code comments.

We even add `/*!` and  `*/` around the rendered markdown, because thanks to this user can just copy paste the code from documentation and it should be immediately compilable by zserio. It not 1:1 code, but at least it's a valid zserio source.

**Comment by fklebert** [comment]
OK, then let's leave it as it is.
I still think that people may accidentally leave out the empty line, because they want to keep their code base tidy. In such a case a warning would be beneficial that a sticky markdown comment is used.
Main use case for markdown comments is still to describe concepts with images/formatting etc., compared to doc comments that should be kept quite lean and mean. So the markdown comment should naturally be floating in my opinion and sticky usage should trigger a warning, similar to the prior "unused documentation comment".

Leave it up to you to close the ticket.

**Comment by mikir** [comment]
OK. I have created a special issue for documentation - #281.

I will close this issue for now. But in case of further troubles with this behavior, please give us a shout and we will implement some new command line option for documentation generator which will disable sticky Markdown documentation comments to be rendered at the beginning of the code block (e.g. '-disableStickyMarkdownComments').
