### ISSUE TITLE
Stricter closing delimiter for markdown blocks

### ISSUE THREAD

**Issue by josephbirkner** [ndsev/zserio#290]
Currently, the (awesome!) markdown comment parser is a bit too lenient when it comes to the delimiter syntax. It allows `/*! markdown stuff */`, note in particular the final `*/` instead of `!*/`. It would be great if zserio could output an error like **"Markdown comments must be ended with !*/"**. This is important because multiple pieces of external tooling of NDS rely on the ability to differentiate the markdown comment by looking at the closing delimiter.

**Comment by mikir** [comment]
OK, I see. The reason why compiler is not stricter is that from compiler point of view markdown comment is a normal comment with correct format '/* */' and it would be weird to report compilation error just because of formatting problem inside the comment.

We even got some complains in the past that to report compilation error just because of bad formatting comment is really weird. Please see https://github.com/ndsev/zserio/issues/74.

Because of that we suggest to implement warning instead of error if the markdown comment is not ended by '!*/'. If this is not enough and you really need compilation error, then we suggest to implement new command line option to treat warnings as errors. Please see https://github.com/ndsev/zserio/issues/48.

What do you think?

**Comment by josephbirkner** [comment]
I suppose a warning would suffice 👍

**Comment by mikir** [comment]
Perfect, we will implement it in the current milestone.
