### ISSUE TITLE
[Java] PubSub missing final for callback declaration used in anonymous class.

### ISSUE THREAD

**Issue by rbudzko** [ndsev/zserio#307]
Hey,

As explained in ticket topic. `final` is missing, so pubsub doesn't compile. Example code generated by `zserio`:
```
public int subscribePoseRaw(
            zserio.runtime.pubsub.PubsubCallback<nds.vehicle.topics.PoseRawTopic> callback,
            java.lang.Object context)
    {
        final zserio.runtime.pubsub.PubsubInterface.Callback onRaw =
            new zserio.runtime.pubsub.PubsubInterface.Callback()
            {
                @Override
                public void invoke(java.lang.String topic, byte[] data)
                {
                    onRawPoseRaw(callback, topic, data);
                }
            };
        return pubsub.subscribe("nds/vehicle/+/pose/raw", onRaw, context);
    }
```

Additionally it would be a good practice to add `final` to all references which are not supposed to change - in example above - to both the `callback` and the `context`.

**Comment by Mi-La** [comment]
Hi Robert. Thanks for the report! Could you please tell us which Java version are you using?
I just tried to verify Java pubsub generator on our Java sample - https://github.com/ndsev/zserio-pubsub-paho-mqtt-java and it compiles correctly.

Zserio supports only Java 8 and higher and it seems that the things have changed in Java 8, please see: https://docs.oracle.com/javase/tutorial/java/javaOO/localclasses.html#accessing-members-of-an-enclosing-class:
> However, starting in Java SE 8, a local class can access local variables and parameters of the enclosing block that are final or effectively final. A variable or parameter whose value is never changed after it is initialized is effectively final.

I suppose that it might be related?

Please also note that we try to use `final` keyword very consistently, but only for local variables and members. Sometime in past we decided not to use `final` for parameters, since we try to keep the habit to never reuse parameter variables and thus we use it as "effectively final" and it seemed useless to specify it explicitly. Moreover it makes the declarations less readable and based also on various discussions on stackoverflow (e.g. [So, always add final to all arguments?](https://stackoverflow.com/questions/500508/why-should-i-use-the-keyword-final-on-a-method-parameter-in-java#answer-10380512)) we just decided not to use it.

However we can discus if its needed in this particular use-case, but if your problem is caused by using of unsupported (i.e. too old) Java version, you will probably face yet other issues.

**Comment by rbudzko** [comment]
Hey Mi-La. Thank you for a quick response. The version is `javac 1.8.0_275` from open jdk (not oracle). Is it possible that effectively final variables are not ported by oracle to open jdk?

I've reproduced the issue with minimal program compiled directly by `javac` without any tooling fat around.

**Comment by Mi-La** [comment]
Hm .. we also use OpenJDK, we even test multiple (sub) versions 1.8.0_282(linux), 1.8.0_241(win64),1.8.0_162 (win32).
Could you please try the [sample](https://github.com/ndsev/zserio-pubsub-paho-mqtt-java) which I mentioned above? You don't need to install Mosquitto, it's just enough to do first two steps from the [readme](https://github.com/ndsev/zserio-pubsub-paho-mqtt-java#usage)(generate Java service API using Zserio and compile the sources with `javac`).

It would be great if you can provide the minimal program here together with the compiler error output so that I can test it also and hopefully understand the problem :-).

**Comment by rbudzko** [comment]
Hey, I managed to find some time to dig into this strange problem and finally... I've discovered the library is working perfectly fine. For a varied reason `javac` of version I've shared earlier was compiling this particular module as `1.7`.

Sorry for a fuss and thank you for your support @Mi-La !

**Comment by Mi-La** [comment]
No problem, good that it works!
