### ISSUE TITLE
Add delta compressed arrays support into the language

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#309]
Add delta compressed arrays into the language which allow users to decrease size of serialized integer arrays.

Suggestion:

```
struct UseOfDeltaListInFuture
{
    varsize numEntries;
    packed varint32 deltaArray[numEntries];
};
```

Users will be responsible for integer ordering in arrays to decrease all differences between sequential data.

If all differences between sequential data fit to the 6 bits, this new feature should use underneath the following invisible schema which implements delta compression array:

```
struct DeltaVarIntList
{
//  varsize numEntries;
    bit:6   numBits;
    varint  element0;
    int<numBits> deltaArray[numEntries - 1];
};
```

**Comment by fklebert** [comment]
The first code block indicates that the user is able to pass the number of entries to the packed array. The second code block indicates that the number of entries is stored within the packed array representation.
Sounds contradicting. Is it intended (or needed) to store the numEntries again?

**Comment by mikir** [comment]
No, this is not necessary. You are right. It is a mistake. I have commented it out.

**Comment by mikir** [comment]
The generic solution for invisible schema of delta compressed integer arrays will look like the following:

```
struct DeltaVarIntList
{
    bit:6   maxBitNumber; // max. bit number to be used for all differences (number from interval <0, 63>)
    varint  element0;     // first original element
    int<maxBitNumber + 1> deltaArray[numEntries - 1]; // all differences between sequential data
};
```

**Comment by mikir** [comment]
Delta compressed arrays could be extended to compound arrays as well using new keyword `packable`. This new keyword could denote which field should be delta compressed if the corresponding compound array is packed. Example:

```
struct TimeStamp 
{ 
    packable varuint seconds; // this field will be delta compressed in packed array 
    varuint nanoseconds; // this field won’t be delta compressed in packed array 
}; 

struct UseOfDeltaListInFuture 
{ 
    varsize numEntries; 
    packed varint32 listB[numEntries]; // packed integer array
    packed TimeStamp listC[numEntries]; // packed compound array according to field ‘seconds’ 
    TimeStamp listD[numEntries]; // normal array without any compression	 
} 
```

**Comment by reinco** [comment]
1. Instead of numBits, store the MSB (most significant bit). That only requires 5 bits instead of 6 (because the maximum varuint value is a 32 bit number, so the most significant bit is 31, which fits in 5 bits)
2. Can you come up with a solution that also works for arrays XY and XYZ coordinates. It is easier to use compared to the delta XY and XYZ arrays currently used. Of course it should not lead to a blob size increase compared to the current solution for such coordinate arrays.

**Comment by mikir** [comment]
@reinco, thanks for the remarks.

You are right, storing MSB saves one bit. We will implement it in this way. However, `var(u)int` can hold 64 bit number, so we need 6 bits in this case.

We are just about to deep investigation how to implement this for generic compound arrays. If we succeed, it will work for arrays of XY and XYZ coordinates as well.

**Comment by Mi-La** [comment]
The error fired when trying to use `packed` keyword on array of 'unpackable' type was changed to a warning, since the generated code is valid and will probably cause only some performance drop. Such packed array should even be binary compatible with an appropriate unpacked array but we don't guarantee it (and thus we don't test it).
