### ISSUE TITLE
Make `java.util.List` optional for java.

### ISSUE THREAD

**Issue by rbudzko** [ndsev/zserio#313]
Would it be possible to add an option to the compiler, so:
```
struct Person(LaneLayoutType layout, bool hasBoundaryGeometry)
{
  Person friends[];
}
```
won't be generating duplicated setter methods in java, like:
```
public void setFriends(zserio.runtime.array.ObjectArray<Friends> friends_)
{
        this.friends_ = friends_;
}

public void setFriends(java.util.List<Friends> friends_)
{
        this.friends_ = new zserio.runtime.array.ObjectArray<Friends>(friends_);
}
```
because many java frameworks bases on "java bean" notation and such a setter is seen as ambiguous. It should be a change possible to achieve, as after generation of our schema `java.uti.List<>` setter is never used and `zserio.runtime.array.ObjectArray<>` is always in use for example by getter.

**Comment by rbudzko** [comment]
I've created an example of what I have in mind in form of PR. The parameters introduction would be specifically for java only. Let me know your thoughts please.

**Comment by mikir** [comment]
Thanks a lot for sharing your ideas.

We were not aware that generated setters are ambiguous for java frameworks. As far as I remember nobody requested `java.util.List` setter and we have added it only for user convenience. I will check it with other users if this is still correct and nobody really needs it.

If so, we would probably just remove `java.util.List` setter. If isn't, we will do it as you suggested and extend the command line. The reason is that we are trying to keep command line as simple as possible not to confuse "not well informed" users.

**Comment by rbudzko** [comment]
Thanks @mikir . 

One example of such ambiguity would be popular library to parse json, fasterxml jackson. Without adding specific annotation two setters with different type makes the framework doubt which type should be used. One could add this annotation, but it defy the purpose of automatic generating sources.

**Comment by rbudzko** [comment]
Thanks for an update @mikir . Would it speed things up if I created a PR for this issue?

**Comment by mikir** [comment]
This is not a big issue. If this blocks you somehow and you need to speed things up, I will re-plan this to the current milestone and we will do it.

**Comment by rbudzko** [comment]
The issue is not blocking. Thanks for putting it into a priority backlog.

**Comment by mikir** [comment]
OK, we will do it in reasonable time to be in the next release.

Btw, PRs in general are pretty welcome. We are even planning to create some simple document 'How to contribute' because of that. Just this particular 'deleting' issue is so easy that it will be quicker for both sides to do it without PR.

**Comment by mikir** [comment]
I have one question, please. I am not familiar with Java Bean but do overloaded methods make problems in general? For example, there is overloaded `write` method as well. Is this ok for your use case? I just would like to have better understanding when overloaded methods can make a problem and when not. Thanks!

**Comment by rbudzko** [comment]
I don't think overloaded methods per se are a problem. It is a known language capability and any serious implementation shall honor it. 

The real problem happens when assumptions (conventions) come into the play for models where a method signature is used to determine model shape ie. unannotated Jackson properties or possibly unannotated Hibernate entities. In this situation setter specifically is found duplicated and the frameworks cannot figure it our which out of two types is a type of corresponding (to the setter) field.

**Comment by mikir** [comment]
Aha, OK. Thanks a lot for the explanation.

The redundant (not used) setter with `java.util.List` has been removed.

**Comment by rbudzko** [comment]
Thank you @mikir . Looking forward to the next release 😄 .
