### ISSUE TITLE
Java: Create string constants for service method names in generated code

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#335]
At the moment the method names of services are generated only as strings in maps, e.g.

```
    methodMap = new java.util.HashMap<java.lang.String, Method>();
    methodMap.put("getServiceDefinition",
        new Method()
        {
            @Override
            public byte[] invoke(byte[] requestData, java.lang.Object context)
                    throws zserio.runtime.ZserioError
            {
                return getServiceDefinitionMethod(requestData, context);
            }
        }
    );
    methodMap.put("getServiceNodeSystemReference",
```
If you want to use annotations in Java this is not possible really. In my Java REST implementation https://github.com/ndsev/zserio-service-rest-java I created string constants which were referred in annotations then. For NDS.Islands I used e.g.:

```
public final static String GET_LAYER_BY_ID = "/getLayerByTileId";
public final static String GET_SERVICE_CAPABILITIES = "/getServiceCapabilities";
...
 
@PostMapping(value = GET_LAYER_BY_ID)
public ResponseEntity<SmartLayerTile> getLayerByTileId(
                      @RequestBody TileId request) throws Exception;
```

I propose to add final static string constants to the generated service code like this:

```
...
 public final static String GET_SERVICE_DEFINITION = "getServiceDefinition";
 public final static String GET_SERVICE_NODE_SYSTEM_REFERENCE = "getServiceNodeSystemReference";
...
 methodMap = new java.util.HashMap<java.lang.String, Method>();
 methodMap.put(GET_SERVICE_DEFINITION,
   new Method()
   {
     @Override public byte[] invoke(byte[] requestData, java.lang.Object context)
                       throws zserio.runtime.ZserioError
     {
       return getServiceDefinitionMethod(requestData, context);
     }
   }
);
methodMap.put(GET_SERVICE_NODE_SYSTEM_REFERENCE,
...
```

This would be 100% backward compatible and allows easier usage of Java annotations.

**Comment by Mi-La** [comment]
We added the constants, but to keep similar concept as is used for SQL databases, the constants have the following naming:
`public static final String ${method.name}_METHOD_NAME = "${method.name}"`.
Which means that the constant names are not in upper case. This is necessary since method names in a service currently doesn't have to be unique in case insensitive comparison. E.g. both "powerOfTwo" and "powerofTwo" are allowed to be present within a single service. If this is not acceptable, we case create a separate issue for it.
Also the `METHOD_NAME` suffix is used to prevent possible clashes. Note that the constants are defined in the the top-level service class and thus the constants could probably clash with `${name}Service` or `${name}Client` inner classes.
