### ISSUE TITLE
Introduce non-explicit empty constructor in C++

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#459]
Currently, Zserio objects in C++ do have the following default constructor:

```
explicit ZserioObject(const allocator_type& allocator = allocator_type()) noexcept;
```

This prevents calling of empty constructor implicitly. Example:

```
ZserioObject zserioObject = {};
```

This could be potentionally cumbersome for example if `ZserioObject` is passed as parameter.

The solution could be to split this constructor as follows:

```
ZserioObject() noexcept;
explicit ZserioObject(const allocator_type& allocator) noexcept;
```

**Comment by Mi-La** [comment]
1. We have split single constructor to empty constructor and constructor with allocator_type
2. Field constructor was improved to support `{}` - i.e. default template parameters were added
   * construction with `{}` cannot work for structures with single field since the constructor is ambiguous (ambiguity with copy constructor...)
3. Note that when structure has optional fields and `{}` is used as a field constructor parameter, it DOES NOT mean that optional field is not present (`NullOpt`) but empty constructor is used to create optional field.
