### ISSUE TITLE
The value ranges of the varsize are 2^36 (68,719,476,736).

### ISSUE THREAD

**Issue by kancve** [ndsev/zserio#464]
Is the description of the document incorrect?

![1](https://user-images.githubusercontent.com/29945891/209777787-06b6e58b-93d6-4fde-bb56-fa400e8205da.png)

![2](https://user-images.githubusercontent.com/29945891/209777844-bbb855b3-5830-495c-8375-76043abd5149.png)

**Comment by mikir** [comment]
Thanks for the note! The documentation is correct, however misleading. We will improve it.

The `varsize` range is really `<0, 2^31-1>` which fits to the 32-signed integer as a maximum unsigned number. We needed this limitation because of Java which uses 32-bits `int` as an index to the array.

The problem in documentation is that only the most significant 3-bits of the last `byte 5` are used for the `varsize` calculation. Or in another words, the exception is thrown during deserialization if value stored in `varsize` is bigger than `2^31-1`.

**Comment by mikir** [comment]
Description of varsize type has been improved in ZserioLanguageOverview and ZserioEncodingGuide documents to be more clear.
