### ISSUE TITLE
Documentation on when C++ exceptions are thrown

### ISSUE THREAD

**Issue by fklebert** [ndsev/zserio#493]
As zserio is not exception free, the use in functional safe systems may sometimes raise questions on when zserio throws exceptions, so that these can potentially be avoided by other means.

We should document the circumstances when zserio throws exceptions and what can be done to ensure that a reader system does not run into these.
One can be that for example the data has to be parsed on a test system before it is shipped to a functional safe system. If the parser does not throw exceptions on the test system it is guaranteed that it also will not throw on the safe system in case the data is still the same (to be safeguarded by signing the data, etc.)

It may sound strange to document that in zserio docs, but it will for sure help anyone deploying zserio to a system that does not allow exceptions. 
In a second step we should think about getting the runtime and generated code exception free.

**Comment by mikir** [comment]
Zserio C++ runtime library together with the C++ generated code can throw a `zserio::CppRuntimeException` in
some rare circumstances, mainly

- during parsing (reading)
- during writing
- in reflection code
- in type info code

Because there are hundreds possibilities when exception `zserio::CppRuntimeException` can be thrown, we will document properly as the first step only exceptions during parsing.
