### ISSUE TITLE
Set cpp allocator tests do not work in CI build with MSVC in Debug

### ISSUE THREAD

**Issue by Mi-La** [ndsev/zserio#589]
Set cpp allocator tests fails in MSVC Debug:

```
The following tests FAILED:
	 28 - ComplexAllocationTest.readConstructor (Exit code 0xc0000409
)
	 29 - ComplexAllocationTest.copyConstructor (Failed)
	 30 - ComplexAllocationTest.moveConstructor (Exit code 0xc0000409
)
	 31 - ComplexAllocationTest.copyAssignmentOperator (Failed)
	 32 - ComplexAllocationTest.moveAssignmentOperator (Exit code 0xc0000409
)
	 33 - ComplexAllocationTest.propagatingCopyConstructor (Exit code 0xc0000409
)
	 34 - ComplexAllocationTest.allocatorConstructor (Failed)
	 35 - ComplexAllocationTest.fieldConstructor (Exit code 0xc0000409
)
	 36 - ComplexAllocationTest.setters (Exit code 0xc0000409
)
	 37 - ComplexAllocationTest.bitSizeOf (Exit code 0xc0000409
)
	 38 - ComplexAllocationTest.initializeOffsets (Exit code 0xc0000409
)
	 39 - ComplexAllocationTest.operatorEquality (Failed)
	 40 - ComplexAllocationTest.hashCode (Failed)
	 41 - ComplexAllocationTest.write (Failed)
	 42 - ComplexAllocationTest.funcConstString (Failed)
	 43 - ComplexAllocationTest.funcConstCompound (Failed)
	 48 - SqlAllocationTest.readWithoutCondition (Failed)
	 49 - SqlAllocationTest.readWithCondition (Failed)
	 50 - SqlAllocationTest.update (Failed)
	 51 - SqlAllocationTest.validateValidDatabase (Failed)
	 52 - SqlAllocationTest.validateInvalidSchema (Failed)
	 53 - SqlAllocationTest.validateInvalidField (Failed)
```

**Comment by mikir** [comment]
The problem was that [checked iterators](https://learn.microsoft.com/en-us/cpp/standard-library/checked-iterators?view=msvc-170) and [debug iterator support](https://learn.microsoft.com/en-us/cpp/standard-library/debug-iterator-support?view=msvc-170) are enabled by default for MSVC Debug builds.

This is controlled by `_ITERATOR_DEBUG_LEVEL` macro:

If `_ITERATOR_DEBUG_LEVEL` is defined as 1 or 2, checked iterators ensure that the bounds of your containers are not overwritten.

If `_ITERATOR_DEBUG_LEVEL` is 0, iterators are not checked.

When `_ITERATOR_DEBUG_LEVEL` is defined as 1, any unsafe iterator use causes a runtime error and the program is terminated.

When `_ITERATOR_DEBUG_LEVEL` is defined as 2, unsafe iterator use causes an assert and a runtime error dialog that lets you break into the debugger.
