### ISSUE TITLE
Fix MISRA C++ 2023 rule 7.11.2 "An array passed as a function argument shall not decay to a pointer"

### ISSUE THREAD

**Issue by mikir** [ndsev/zserio#660]
There is a corresponding SonarCloud rule [S945](https://sonarcloud.io/organizations/ndsev/rules?open=cpp%3AS945&q=s945) which is able to catch some problems in the C++ runtime library. For example in `CppRuntimeException.h`:

```
return exception << "vector([...], " << value.size() << ")";
```

The problem in the previous example is that the string literal `"vector([...]),"` is silently casted from the `const char[N]` to the `const char*`.

Enable this rule and fix all found issues.

**Comment by Mi-La** [comment]
We need support for `const char*` overload to keep convenient usage of `CppRuntimeException`. The exception is thrown only from Zserio controlled code and we can ensure that all strings are properly zero-terminated.

Note that it's not trivial to add an overload for `const char (&message)[N]` since the overload resolution would still choose `const char*` overload.
Also we have use-cases where we currently need to support `const char*` - e.g. exception throw by zserio enums. It could be possible to change it, but it would be significant amount of work.

Currently we have resolved 3 issues in  [SonarCoud](https://sonarcloud.io/project/issues?rules=cpp%3AS945&issueStatuses=ACCEPTED%2CFALSE_POSITIVE&id=ndsev_zserio).
