### ISSUE TITLE
@see can not refer to not directly imported elements

### ISSUE THREAD

**Issue by CzB404** [ndsev/zserio#74]
During documentation generation `@see` can not refer to elements that are not directly imported.
E.g. I have an `all.zs` that `import`s
`a.zs`:
```
struct A
{
    varint x;
};
```
and `b.zs`:
```
struct B
{
    /**
     * @see A
     */
    varint y;
};
```

Currently even code generation fails because it cannot resolve A in the documentation comment, which is wierd, because I'm not generating documentation. I have to `import a.A`, even though the code itself does not use it.

If there has to be some sort of import, then my recommendation would be something like the following:
```
/// @docimport a.A

struct B
{
    /**
     * @see A
     */
    varint y;
};
```
This way comments are true comments, but the documentation parser has the necessary information to link to the appropriate doc page.

**Comment by mikir** [comment]
Thanks for this idea. I understand your use case. It might be that compiler should not be so strict. We will think about this. However, it's legal that compilation fails only because documentation comment. For example, documentation comment can be badly formatted. What we were trying to solve here is that if something compiles, e

**Comment by mikir** [comment]
This has been already solved during upgrade to ANTLR4 within scope of issue #123. Now, only warning is fired in this case.
